---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[docker::default]
    attributes:
  - name: install
      run_list:
        - recipe[docker::install]
      attributes:
  - name: docker-deploy
      run_list:
        - recipe[docker::docker-deploy]
      attributes:
